version: "3"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:${PROMETHEUS_VERSION}
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
    volumes:
      - ./resources/configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./resources/rules:/etc/prometheus/rules
    ports:
      - ${PROMETHEUS_PORT}:9090
    restart: unless-stopped
