version: "3"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:${GRAFANA_VERSION}
    command:
      - "--config=/etc/grafana/grafana.ini"
    volumes:
      - ./resources/configs/sample.ini:/etc/grafana/grafana.ini
    ports:
      - ${GRAFANA_PORT}:3000
    restart: unless-stopped
